package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDoctorAutoFixAppliesDeadCode(t *testing.T) {
	dir := t.TempDir()
	path := writeTempGo(t, dir, "f.go", "package x\n\nfunc used() int { return 1 }\n\nfunc main() { used() }\n\nfunc unused() int { return 2 }\n")

	restore := swapVerifyGate(func(string) error { return nil })
	defer restore()

	applied, reverted, failed, err := doctorAutoFix(dir, fixLevelSafe, "")
	if err != nil {
		t.Fatalf("doctorAutoFix: %v", err)
	}
	if applied != 1 || reverted != 0 || failed != 0 {
		t.Fatalf("counts: applied=%d reverted=%d failed=%d", applied, reverted, failed)
	}
	got := readFile(t, path)
	if strings.Contains(got, "func unused") {
		t.Fatalf("unused should have been deleted; got:\n%s", got)
	}
	if !strings.Contains(got, "func used") {
		t.Fatalf("used should have remained; got:\n%s", got)
	}
}

func TestDoctorAutoFixRevertsOnRedGate(t *testing.T) {
	dir := t.TempDir()
	path := writeTempGo(t, dir, "f.go", "package x\n\nfunc used() int { return 1 }\n\nfunc main() { used() }\n\nfunc unused() int { return 2 }\n")
	orig := readFile(t, path)

	restore := swapVerifyGate(func(string) error { return fmt.Errorf("boom") })
	defer restore()

	applied, reverted, failed, err := doctorAutoFix(dir, fixLevelSafe, "")
	if err != nil {
		t.Fatalf("doctorAutoFix: %v", err)
	}
	if applied != 0 || reverted != 1 || failed != 0 {
		t.Fatalf("counts: applied=%d reverted=%d failed=%d", applied, reverted, failed)
	}
	if got := readFile(t, path); got != orig {
		t.Fatalf("fix should have been reverted; got:\n%s", got)
	}
}

func TestDoctorCommandRejectsBadFixLevel(t *testing.T) {
	dir := t.TempDir()
	if err := doctorCommand([]string{dir, "--fix", "--fix-level", "bogus"}); err == nil {
		t.Fatal("expected error for invalid --fix-level")
	}
}

func TestDoctorAutoFixStageOKDespiteFailedFixes(t *testing.T) {
	restore := swapDoctorAutoFixFn(func(string, string, string) (int, int, int, error) {
		return 1, 2, 5, nil
	})
	defer restore()

	stage, err := doctorAutoFixStage(".", fixLevelSafe, "")
	if err != nil {
		t.Fatalf("doctorAutoFixStage: %v", err)
	}
	if !stage.ok {
		t.Fatal("autofix stage should stay ok=true even when some fixes failed to apply")
	}
	if !strings.Contains(stage.info, "5 not applied") {
		t.Fatalf("info should report the failed count; got %q", stage.info)
	}
}

func TestDoctorAutoFixFormatsUntouchedFile(t *testing.T) {
	dir := t.TempDir()
	writeTempGo(t, dir, "f.go", "package x\n\nfunc used() int { return 1 }\n\nfunc main() { used() }\n")
	messy := writeTempGo(t, dir, "messy.go", "package x\n\nfunc   Messy(  )   int {\n\treturn    7\n}\n")

	restore := swapVerifyGate(func(string) error { return nil })
	defer restore()

	if _, _, _, err := doctorAutoFix(dir, fixLevelSafe, ""); err != nil {
		t.Fatalf("doctorAutoFix: %v", err)
	}
	got := readFile(t, messy)
	want := "package x\n\nfunc Messy() int {\n\treturn 7\n}\n"
	if got != want {
		t.Fatalf("messy.go should have been gofmt'd even though no lint rule touched it; got:\n%s", got)
	}
}

// TestDoctorAutoFixRespectsConfigWalkSkips verifies that doctor --fix does not
// touch files excluded by the walk: section of .gorefactor.yaml. Generated
// files with a skip_dir_segment or listed in skip_files must be left alone
// even when they contain fixable issues.
func TestDoctorAutoFixRespectsConfigWalkSkips(t *testing.T) {
	dir := t.TempDir()

	// Hand-written file with a fixable issue.
	src := writeTempGo(t, dir, "main.go", "package x\n\nfunc used() int { return 1 }\n\nfunc main() { used() }\n\nfunc unused() int { return 2 }\n")

	// Generated file in a skipped subdirectory — must not be modified.
	genDir := filepath.Join(dir, "gen")
	if err := os.MkdirAll(genDir, 0755); err != nil {
		t.Fatal(err)
	}
	genFile := filepath.Join(genDir, "generated.go")
	genContent := "// Code generated by tool. DO NOT EDIT.\n\npackage gen\n\nfunc GenUnused() int { return 99 }\n"
	if err := os.WriteFile(genFile, []byte(genContent), 0644); err != nil {
		t.Fatal(err)
	}

	// Config that skips the gen/ directory.
	cfgPath := filepath.Join(dir, ".gorefactor.yaml")
	cfgContent := "walk:\n  skip_dir_segments:\n    - gen\n"
	if err := os.WriteFile(cfgPath, []byte(cfgContent), 0644); err != nil {
		t.Fatal(err)
	}

	restore := swapVerifyGate(func(string) error { return nil })
	defer restore()

	if _, _, _, err := doctorAutoFix(dir, fixLevelSafe, cfgPath); err != nil {
		t.Fatalf("doctorAutoFix: %v", err)
	}

	// The generated file must be byte-for-byte identical to what we wrote.
	if got := readFile(t, genFile); got != genContent {
		t.Fatalf("generated file was modified despite being in a skip_dir_segment:\n%s", got)
	}

	// The hand-written file should have been processed (unused func removed).
	if got := readFile(t, src); strings.Contains(got, "func unused") {
		t.Fatalf("expected unused func to be removed from hand-written file; got:\n%s", got)
	}
}

// TestDoctorLintStageRespectsConfigWalkSkips verifies that doctorLintStage
// does not report issues in directories excluded by the walk config.
func TestDoctorLintStageRespectsConfigWalkSkips(t *testing.T) {
	dir := t.TempDir()

	// Create a very large generated file in a skipped directory that would
	// normally trigger the file-size lint rule.
	genDir := filepath.Join(dir, "gen")
	if err := os.MkdirAll(genDir, 0755); err != nil {
		t.Fatal(err)
	}
	var sb strings.Builder
	sb.WriteString("// Code generated by tool. DO NOT EDIT.\n\npackage gen\n\n")
	for i := range 600 {
		fmt.Fprintf(&sb, "func F%d() int { return %d }\n", i, i)
	}
	if err := os.WriteFile(filepath.Join(genDir, "big.go"), []byte(sb.String()), 0644); err != nil {
		t.Fatal(err)
	}

	cfgPath := filepath.Join(dir, ".gorefactor.yaml")
	cfgContent := "walk:\n  skip_dir_segments:\n    - gen\nlimits:\n  file_length_source: 500\n"
	if err := os.WriteFile(cfgPath, []byte(cfgContent), 0644); err != nil {
		t.Fatal(err)
	}

	stage, err := doctorLintStage(dir, cfgPath)
	if err != nil {
		t.Fatalf("doctorLintStage: %v", err)
	}
	if !stage.ok {
		t.Fatalf("expected lint stage to pass when oversized file is in skipped dir; got: %s", stage.info)
	}
}

func swapDoctorAutoFixFn(fn func(string, string, string) (int, int, int, error)) func() {
	prev := doctorAutoFixFn
	doctorAutoFixFn = fn
	return func() { doctorAutoFixFn = prev }
}
