package main

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/chrisophus/gorefactor/analyzer"
)

func architectCommand(args []string) error {
	suggest := false
	root := "."
	outPath := ""
	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "--suggest":
			suggest = true
		case "--output", "-o":
			if i+1 < len(args) {
				outPath = args[i+1]
				i++
			}
		default:
			if !strings.HasPrefix(args[i], "--") {
				root = args[i]
			}
		}
	}
	if !suggest {
		return fmt.Errorf("usage: architect --suggest [--output <path>] [dir]")
	}

	graph, err := analyzer.NewPackageGraph(root)
	if err != nil {
		return err
	}

	var out io.Writer = os.Stdout
	if outPath != "" {
		f, err := os.Create(outPath)
		if err != nil {
			return err
		}
		defer f.Close()
		out = f
	}
	_, err = io.WriteString(out, generateArchYAML(graph))
	return err
}

func generateArchYAML(graph *analyzer.PackageGraph) string {
	pkgs := graph.AllPackages()
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].Path < pkgs[j].Path })

	// Detect component name collisions (e.g., foo/bar and foo_bar both -> foo_bar)
	names := make(map[string]string)
	for _, p := range pkgs {
		if p.Path == "" {
			continue
		}
		name := archComponentName(p.Path)
		if existing, ok := names[name]; ok && existing != p.Path {
			// Component name collision detected; return empty to indicate error
			// (caller should handle this gracefully)
			return fmt.Sprintf("# ERROR: component name collision: %q generated from both %q and %q\n# Fix: rename packages or use explicit component names\n", name, existing, p.Path)
		}
		names[name] = p.Path
	}

	var b strings.Builder
	b.WriteString("version: 3\n")
	b.WriteString("# Generated by `gorefactor architect --suggest`.\n")
	b.WriteString("# Components mirror current package structure; deps mirror the\n")
	b.WriteString("# existing import graph. Edit before committing — tighten by\n")
	b.WriteString("# removing dep entries you want to forbid.\n\n")
	b.WriteString("allow:\n  depOnAnyVendor: true\n\n")
	b.WriteString("components:\n")
	for _, p := range pkgs {
		if p.Path == "" {
			continue
		}
		fmt.Fprintf(&b, "  %s: { in: %s/** }\n", archComponentName(p.Path), p.Path)
	}
	b.WriteString("\ndeps:\n")
	for _, p := range pkgs {
		if p.Path == "" {
			continue
		}
		deps := archLocalDeps(p, pkgs)
		if len(deps) == 0 {
			fmt.Fprintf(&b, "  %s: { mayDependOn: [] }\n", archComponentName(p.Path))
			continue
		}
		fmt.Fprintf(&b, "  %s:\n    mayDependOn:\n", archComponentName(p.Path))
		for _, d := range deps {
			fmt.Fprintf(&b, "      - %s\n", d)
		}
	}
	return b.String()
}

// archLocalDeps returns the component names that p actually imports
// today (suffix-matched against the local package set, preferring longest match).
func archLocalDeps(p *analyzer.PackageInfo, pkgs []*analyzer.PackageInfo) []string {
	var deps []string
	seen := make(map[string]bool)
	for _, imp := range p.Imports {
		var bestMatch *analyzer.PackageInfo
		for _, q := range pkgs {
			if q.Path == "" || q.Path == p.Path {
				continue
			}
			if imp == q.Path || strings.HasSuffix(imp, "/"+q.Path) {
				// Prefer the longest matching package path to avoid ambiguity
				// (e.g., both "bar" and "foo/bar" match import "github.com/foo/bar")
				if bestMatch == nil || len(q.Path) > len(bestMatch.Path) {
					bestMatch = q
				}
			}
		}
		if bestMatch != nil {
			name := archComponentName(bestMatch.Path)
			if !seen[name] {
				seen[name] = true
				deps = append(deps, name)
			}
		}
	}
	sort.Strings(deps)
	return deps
}

func archComponentName(path string) string {
	return strings.ReplaceAll(path, "/", "_")
}
