package doctor

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/chrisophus/gorefactor/analyzer"
)

func TestFilterFindingsDropsGeneratedAndSkipped(t *testing.T) {
	root := t.TempDir()
	gen := "// Code generated by protoc. DO NOT EDIT.\npackage p\n"
	if err := os.WriteFile(filepath.Join(root, "gen.go"), []byte(gen), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "real.go"), []byte("package p\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	findings := []Finding{
		{File: "gen.go", Rule: "r", Message: "m"},
		{File: "real.go", Rule: "r", Message: "m"},
		{File: "vendor/x/y.go", Rule: "r", Message: "m"},
		{Rule: "api-removed", Message: "fileless findings pass through"},
	}
	out := filterFindings(findings, root, analyzer.DefaultWalkOptions())
	if len(out) != 2 {
		t.Fatalf("want real.go + fileless, got %+v", out)
	}
	if out[0].File != "real.go" || out[1].Rule != "api-removed" {
		t.Fatalf("unexpected survivors: %+v", out)
	}
}

func TestNormalizeFindingsStripsRootFromMessages(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "a.go"), []byte("package p\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	abs := filepath.Join(root, "a.go")
	// The same finding as produced in the working tree (relative paths) and in
	// a baseline worktree (absolute paths under the worktree root) must
	// fingerprint identically — this is what keeps baseline marking working.
	fromWorktree := normalizeFindings([]Finding{{
		File: abs, Rule: "dup", Message: "duplicated at " + abs + ":10-20",
	}}, root, analyzer.DefaultWalkOptions())
	fromRelative := normalizeFindings([]Finding{{
		File: "a.go", Rule: "dup", Message: "duplicated at a.go:99-120",
	}}, ".", analyzer.DefaultWalkOptions())
	if len(fromWorktree) != 1 || len(fromRelative) != 1 {
		t.Fatalf("both findings should survive: %v %v", fromWorktree, fromRelative)
	}
	if fromWorktree[0].Fingerprint != fromRelative[0].Fingerprint {
		t.Fatalf("fingerprint mismatch:\n%+v\n%+v", fromWorktree[0], fromRelative[0])

	}
}
