package changectx

import (
	"os"
	"path/filepath"
	"testing"
)

func TestClassifyPathsByClass(t *testing.T) {
	repo := t.TempDir()
	cases := []struct {
		path      string
		want      Class
		generated bool
	}{
		{"internal/store/user.go", ClassSource, false},
		{"internal/store/user_test.go", ClassTest, false},
		{"internal/store/testdata/golden.json", ClassTest, false},
		{"vendor/example.com/dep/dep.go", ClassVendored, false},
		{"third_party/lib/lib.go", ClassVendored, false},
		{"db/migrations/0001_users.sql", ClassMigration, false},
		{"schema/000123_add_index.sql", ClassMigration, false},
		{"go.sum", ClassLockfile, true},
		{"web/package-lock.json", ClassLockfile, false},
		{"api/user.pb.go", ClassGenerated, true},
		{"api/zz_generated.deepcopy.go", ClassGenerated, true},
		{"api/schema.gen.go", ClassGenerated, true},
		{"internal/kind_string.go", ClassGenerated, true},
		{"internal/oas_client.go", ClassGenerated, true},
		{"README.md", ClassOther, false},
	}
	for _, tc := range cases {
		class, gen := classify(repo, change{path: tc.path, status: "M"})
		if class != tc.want {
			t.Errorf("%s: class %q, want %q", tc.path, class, tc.want)
		}
		if gen != tc.generated {
			t.Errorf("%s: generated %v, want %v", tc.path, gen, tc.generated)
		}
	}
}

func TestClassifyGeneratedHeader(t *testing.T) {
	repo := t.TempDir()
	write := func(name, content string) {
		t.Helper()
		p := filepath.Join(repo, name)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	write("marked.go", "// Code generated by stringer. DO NOT EDIT.\n\npackage x\n")
	write("blockmarked.go", "/* Code generated by protoc. DO NOT EDIT. */\npackage x\n")
	write("buildtagged.go", "//go:build linux\n\n// Code generated by mockgen. DO NOT EDIT.\n\npackage x\n")
	// The negative case this classifier exists for: a hand-written file that
	// talks about the convention must stay reviewable.
	write("discusses.go", `// A file whose header says "Code generated by X. DO NOT EDIT." is machine
// output, and this classifier must not hide this file because of that line.
package x

const marker = "Code generated by X. DO NOT EDIT."
`)
	write("mentions_in_body.go", "package x\n\n// Code generated by X. DO NOT EDIT.\nfunc f() {}\n")
	write("plain.go", "package x\n")

	cases := map[string]bool{
		"marked.go":           true,
		"blockmarked.go":      true,
		"buildtagged.go":      true,
		"discusses.go":        false,
		"mentions_in_body.go": false,
		"plain.go":            false,
	}
	for name, want := range cases {
		if got := hasGeneratedHeader(repo, name); got != want {
			t.Errorf("hasGeneratedHeader(%s) = %v, want %v", name, got, want)
		}
		class, gen := classify(repo, change{path: name, status: "M"})
		if gen != want {
			t.Errorf("classify(%s) generated = %v, want %v", name, gen, want)
		}
		wantClass := ClassSource
		if want {
			wantClass = ClassGenerated
		}
		if class != wantClass {
			t.Errorf("classify(%s) class = %q, want %q", name, class, wantClass)
		}
	}
}

func TestClassifyDeletedFileSkipsHeaderRead(t *testing.T) {
	repo := t.TempDir()
	class, gen := classify(repo, change{path: "gone.go", status: "D"})
	if gen || class != ClassSource {
		t.Errorf("deleted file classified %q generated=%v, want source/false", class, gen)
	}
}
