package main

func toolCatalog() []toolDef {
	return []toolDef{
		// sense (read-only)
		tool("list_symbols", "List funcs/methods in a file.",
			obj(map[string]any{"file": strProp("path")}, "file")),
		tool("read_excerpt", "Read lines from a file (max 160). Prefer read_file to see a whole file in one call.",
			obj(map[string]any{"file": strProp("path"),
				"start_line": intProp("1-based"), "end_line": intProp("inclusive")}, "file")),
		tool("read_file", "Read an ENTIRE file (line-numbered, up to 600 lines) in one call. Use this to orient on each target file once, up front — do not page or re-read.",
			obj(map[string]any{"file": strProp("path")}, "file")),
		tool("analyze_file_size", "File line count and extraction hints.",
			obj(map[string]any{"file": strProp("path")}, "file")),
		tool("find_references", "Lines mentioning a symbol across the repo.",
			obj(map[string]any{"symbol": strProp("identifier")}, "symbol")),
		tool("inspect_file", "One-page file summary: declarations, sizes, lint hints, and extraction candidates.",
			obj(map[string]any{"file": strProp("path")}, "file")),
		tool("skeleton", "Show a file with function bodies replaced by stub comments — fast structural overview.",
			obj(map[string]any{"file": strProp("path")}, "file")),
		tool("review_changes", "Per-function quality regression report vs a git ref (line growth, complexity, nesting).",
			obj(map[string]any{"ref": strProp("git ref to compare against, default HEAD")})),
		tool("lint_path", "Run gorefactor lint on a path and return findings with autofixCmd hints.",
			obj(map[string]any{"path": strProp("directory or file to lint, default '.'")})),

		// mutation
		tool("extract_method", "Extract lines into a new function. Get line numbers via list_symbols+read_excerpt first.",
			obj(map[string]any{
				"file":              strProp("path"),
				"start_line":        intProp("first line (1-based)"),
				"end_line":          intProp("last line (inclusive)"),
				"new_function_name": strProp("new function name"),
			}, "file", "start_line", "end_line", "new_function_name")),
		tool("rename_declaration", "Rename an unexported declaration package-wide. Supply exactly one of function/method/type — the symbol's current identifier.",
			obj(map[string]any{"file": strProp("path"),
				"function": strProp("function name (top-level func)"),
				"method":   strProp("method name"),
				"type":     strProp("type name"),
				"new_name": strProp("new identifier")}, "file", "new_name")),
		tool("replace_code", "Replace a complete statement inside a function.",
			obj(map[string]any{"file": strProp("path"), "function": strProp("enclosing func"),
				"code_pattern": strProp("exact statement to replace"), "replacement_code": strProp("replacement")},
				"file", "function", "code_pattern", "replacement_code")),
		tool("insert_code", "Insert a declaration into a file.",
			obj(map[string]any{"file": strProp("path"),
				"location_type":   strProp("at_end|after_function|before_function|at_beginning"),
				"anchor_function": strProp("anchor (for *_function)"),
				"code_snippet":    strProp("full declaration")}, "file", "location_type", "code_snippet")),
		tool("create_file", "Create a new Go file.",
			obj(map[string]any{"file": strProp("path"),
				"code_snippet": strProp("full file including package clause")}, "file", "code_snippet")),
		tool("move_method", "Move a method to another file.",
			obj(map[string]any{"file": strProp("source"), "method": strProp("method name"),
				"receiver_type": strProp("receiver type"), "new_file": strProp("destination")},
				"file", "method", "receiver_type", "new_file")),
		tool("move_function", "Move a top-level function (no receiver) to another file.",
			obj(map[string]any{"file": strProp("source"), "function": strProp("function name"),
				"new_file": strProp("destination")},
				"file", "function", "new_file")),
		tool("delete_declaration", "Delete a func/method/type declaration. Supply exactly one of function/method/type — the symbol's identifier.",
			obj(map[string]any{"file": strProp("path"),
				"function": strProp("function name (top-level func)"),
				"method":   strProp("method name"),
				"type":     strProp("type name")}, "file")),
		tool("remove_code_block", "Remove a block matching an exact pattern.",
			obj(map[string]any{"file": strProp("path"), "code_pattern": strProp("exact block")},
				"file", "code_pattern")),
		tool("split_file", "Auto-split an oversized file by grouping related declarations into sibling files.",
			obj(map[string]any{"file": strProp("path to the oversized file")}, "file")),
		tool("wrap_errors", "Rewrite bare 'return err' statements inside an 'if err != nil' block to use fmt.Errorf wrapping.",
			obj(map[string]any{"file": strProp("path"), "function": strProp("enclosing function name")},
				"file", "function")),
		tool("set_doc", "Set or replace the godoc comment on a top-level declaration.",
			obj(map[string]any{
				"file":        strProp("path"),
				"declaration": strProp("name of the func/type/var/const"),
				"doc":         strProp("doc comment text (the // prefix is added automatically)"),
			}, "file", "declaration", "doc")),
		tool("change_signature", "Add, remove, or rename a parameter of a function/method AND update every call site — one op. Prefer this over manually rewriting a signature and its callers.",
			obj(map[string]any{
				"file":       strProp("path"),
				"symbol":     strProp("function name, or Receiver:Method for a method"),
				"mode":       strProp("add_param | remove_param | rename_param"),
				"param_spec": strProp(`add_param: "name type", e.g. "ctx context.Context"`),
				"position":   intProp("add_param: 0-based index for the new param (default: append at end)"),
				"call_value": strProp(`add_param: expression to pass at every call site, e.g. "ctx" or "1"`),
				"param":      strProp("remove_param: parameter name or 0-based index to remove"),
				"old_name":   strProp("rename_param: current parameter name"),
				"new_name":   strProp("rename_param: new parameter name"),
			}, "file", "symbol", "mode")),

		// notes (persistent across sessions)
		tool("note", "Record a durable fact for future sessions in .gorefactor/notes.md. Use for repo facts, failed strategies, flaky tests, or open punts a later session would otherwise re-discover.",
			obj(map[string]any{
				"category": strProp("repo_fact | failed_strategy | flaky_test | open_punt"),
				"text":     strProp("the fact to record, one concise sentence"),
			}, "text")),

		// feedback (grow the toolset)
		tool("friction", "Report that the task SUCCEEDED but a gorefactor command was missing or awkward and you had to chain several tools for what should be one op. Non-terminal — record it, then keep working and call finish. This is the main signal used to grow the toolset.",
			obj(map[string]any{
				"missing_command":       strProp("the gorefactor command that would have made this one step, e.g. 'change-signature --add-param'"),
				"suggested_syntax":      strProp("proposed one-shot invocation"),
				"workaround_steps":      strProp("the clumsy tool sequence you actually used, one step per line"),
				"estimated_steps_saved": intProp("how many tool calls the missing command would have saved"),
			}, "missing_command", "suggested_syntax")),

		// control
		tool("report", "Return the answer for an analysis-only task and finish WITHOUT the build/test gate. Use for find-callers / find-uses / \"where is X\" questions.",
			obj(map[string]any{"answer": strProp("the answer")}, "answer")),
		tool("run_gate", "Run go build+test and report (advisory, non-terminal).", obj(map[string]any{})),
		tool("finish", "Mark task complete and run the authoritative gate.", obj(map[string]any{})),
		tool("punt", "Give up; task cannot be done with these tools. If the blocker is a MISSING gorefactor capability (not a judgement call), also fill missing_command/suggested_syntax so the senior can add the command.",
			obj(map[string]any{
				"reason":           strProp("why"),
				"missing_command":  strProp("optional: the gorefactor command whose absence blocks this task"),
				"suggested_syntax": strProp("optional: proposed invocation of that command"),
			}, "reason")),
		tool("insert_switch_case", "Add a case to the expression switch inside a function (inserted before default, else at end). Use to wire a new dispatch branch instead of rewriting the whole switch.",
			obj(map[string]any{
				"file":      strProp("path"),
				"symbol":    strProp("enclosing function name, or Receiver:Method"),
				"case_expr": strProp(`the case expression, e.g. "replace_body"`),
				"body":      strProp("the case body statements"),
			}, "file", "symbol", "case_expr")),
		tool("insert_map_entry", "Append an element to a composite literal — a package-level map/slice var, or the literal a func returns (e.g. a catalog builder). Use to add a map key or a slice element without rewriting the literal.",
			obj(map[string]any{
				"file":    strProp("path"),
				"target":  strProp("the var name, or the func whose returned literal to extend"),
				"element": strProp(`the new element text, e.g. "foo": true, or a full expression`),
			}, "file", "target", "element")),
		tool("replace_in_literal", "Replace text inside a single string literal anywhere in a file (including a package-level prompt/const), AST-scoped so surrounding code is never touched. Match must be unambiguous.",
			obj(map[string]any{
				"file": strProp("path"),
				"old":  strProp("substring to find inside one string literal"),
				"new":  strProp("replacement text"),
			}, "file", "old", "new")),
		tool("replace_body", "Replace the entire body of a named function or method.",
			obj(map[string]any{
				"file":   strProp("path"),
				"symbol": strProp("function name, or Receiver:Method for a method"),
				"body":   strProp("new body statements (without the outer braces)"),
			}, "file", "symbol", "body")),
		tool("add_field", "Add a field to a struct, optionally rewriting positional literals to keyed form. Prefer this over hand-editing a struct and its literals.",
			obj(map[string]any{
				"file":            strProp("path"),
				"struct":          strProp("struct type name"),
				"field":           strProp(`"Name Type [tag]", e.g. "Timeout int"`),
				"update_literals": map[string]any{"type": "boolean", "description": "also rewrite positional composite literals to keyed form"},
			}, "file", "struct", "field")),
		tool("change_receiver", "Switch a method's receiver between value and pointer form (warns about copy-semantics).",
			obj(map[string]any{
				"file":        strProp("path"),
				"type_method": strProp("Type:Method, e.g. Counter:Inc"),
				"mode":        strProp("pointer | value"),
			}, "file", "type_method", "mode")),
		tool("extract_interface", "Generate an interface declaration from a type's exported method set.",
			obj(map[string]any{
				"file":           strProp("path"),
				"type":           strProp("concrete type name"),
				"interface_name": strProp("name for the generated interface"),
			}, "file", "type", "interface_name")),
		tool("inline", "Inline a simple function into its call sites and delete it (refuses anything non-trivial).",
			obj(map[string]any{
				"file":     strProp("path"),
				"function": strProp("top-level function name to inline"),
			}, "file", "function")),
		tool("replace_text", "Literal text replace scoped to a function/method body (finer than replace_code; no statement match needed).",
			obj(map[string]any{
				"file":   strProp("path"),
				"symbol": strProp("enclosing function name, or Receiver:Method"),
				"old":    strProp("literal text to find in the body"),
				"new":    strProp("replacement text"),
			}, "file", "symbol", "old", "new")),
		tool("add_test", "Scaffold a table-driven test for an exported function or method.",
			obj(map[string]any{
				"file":   strProp("path"),
				"symbol": strProp("exported function name, or Receiver:Method"),
			}, "file", "symbol")),
	}
}
